from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import polars as pl

from spiel_des_jahres.ratings import reviews_jl_to_polars

LOGGER = logging.getLogger(__name__)


def arg_parse() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update kritikenrundschau.csv with new reviews from a .jl file.",
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Path to the .jl file generated by the spider.",
    )
    parser.add_argument(
        "--csv",
        "-c",
        type=Path,
        default=Path(__file__).parent / "data" / "kritikenrundschau.csv",
        help="Path to the kritikenrundschau.csv file.",
    )
    parser.add_argument(
        "--dry-run",
        "-n",
        action="store_true",
        help="Do not write to the CSV file.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="count",
        default=0,
        help="Increase verbosity",
    )
    return parser.parse_args()


def main() -> None:
    args = arg_parse()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        stream=sys.stderr,
    )

    if not args.input.exists():
        LOGGER.error("Input file <%s> does not exist.", args.input)
        sys.exit(1)

    LOGGER.info("Processing new reviews from <%s>", args.input)
    # This uses the existing helper from ratings.py
    new_data = reviews_jl_to_polars(args.input)
    LOGGER.info("Extracted %d items from .jl file", len(new_data))

    if not args.csv.exists():
        LOGGER.warning("CSV file <%s> does not exist. Creating new one.", args.csv)
        if not args.dry_run:
            args.csv.parent.mkdir(parents=True, exist_ok=True)
            new_data.write_csv(args.csv)
        return

    LOGGER.info("Reading existing data from <%s>", args.csv)
    # Ensure bgg_id is read as Int64 to match schema
    existing_data = pl.read_csv(args.csv, schema_overrides={"bgg_id": pl.Int64})

    # Combine data using 'diagonal' concatenation
    # This automatically adds new columns if new reviewers are found
    combined = pl.concat([existing_data, new_data], how="diagonal")

    # Deduplicate by URL and Name
    # We sort by bgg_id (descending, nulls last) so that if we have a match,
    # the version with a manually filled bgg_id is kept during unique()
    combined = combined.sort("bgg_id", descending=True, nulls_last=True)
    combined = combined.unique(
        subset=["url", "name"],
        keep="first",
        maintain_order=False,
    )

    # Final sort by date and name for consistent CSV order
    combined = combined.sort("date_published", "name")

    if args.dry_run:
        LOGGER.info("Dry run: not writing to <%s>", args.csv)
        # Show a preview of columns and rows
        print(combined)
    else:
        LOGGER.info("Writing updated data to <%s>", args.csv)
        combined.write_csv(args.csv)
        LOGGER.info("Successfully updated CSV.")


if __name__ == "__main__":
    main()
