from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import polars as pl
from thefuzz import process  # type: ignore[import-untyped]

from spiel_des_jahres.ratings import reviews_jl_to_polars

LOGGER = logging.getLogger(__name__)

FUZZY_MATCH_THRESHOLD = 90


def arg_parse() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update kritikenrundschau.csv with new reviews from a .jl file.",
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Path to the .jl file generated by the spider.",
    )
    parser.add_argument(
        "--csv",
        "-c",
        type=Path,
        default=Path(__file__).parent / "data" / "kritikenrundschau.csv",
        help="Path to the kritikenrundschau.csv file.",
    )
    parser.add_argument(
        "--bgg-games",
        "-b",
        type=Path,
        default=Path(__file__).parent.parent.parent
        / "board-game-data"
        / "scraped"
        / "bgg_GameItem.csv",
        help="Path to the bgg_GameItem.csv file for BGG ID matching.",
    )
    parser.add_argument(
        "--dry-run",
        "-n",
        action="store_true",
        help="Do not write to the CSV file.",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="count",
        default=0,
        help="Increase verbosity",
    )
    return parser.parse_args()


def find_bgg_ids(
    df: pl.DataFrame,
    bgg_games_path: Path,
) -> pl.DataFrame:
    """Try to find BGG IDs for games with missing IDs using exact and fuzzy matching."""
    if not bgg_games_path.exists():
        LOGGER.warning(
            "BGG games file <%s> not found. Skipping ID matching.",
            bgg_games_path,
        )
        return df

    if (missing_count := df.filter(pl.col("bgg_id").is_null()).height) == 0:
        return df

    LOGGER.info("Attempting to find BGG IDs for %d games...", missing_count)

    bgg_lf = pl.scan_csv(bgg_games_path, schema_overrides={"bgg_id": pl.Int64}).select(
        "bgg_id",
        "name",
        name_lower=pl.col("name").str.to_lowercase(),
    )

    # 1. Try exact matching (case-insensitive)
    bgg_exact = bgg_lf.with_columns(count=pl.len().over("name_lower"))

    df = (
        df.lazy()
        .with_columns(name_lower=pl.col("name").str.to_lowercase())
        .join(
            bgg_exact.filter(pl.col("count") == 1).select("bgg_id", "name_lower"),
            on="name_lower",
            how="left",
            suffix="_matched",
        )
        .join(
            bgg_exact.filter(pl.col("count") > 1)
            .select("name_lower")
            .unique()
            .with_columns(is_ambiguous=pl.lit(value=True)),
            on="name_lower",
            how="left",
        )
        .with_columns(bgg_id=pl.coalesce("bgg_id", "bgg_id_matched"))
        .collect()
    )

    for name in df.filter(
        pl.col("is_ambiguous").fill_null(value=False) & pl.col("bgg_id").is_null(),
    )["name"].unique():
        LOGGER.warning(
            "Exact match skipped for '%s' because of BGG name ambiguity.",
            name,
        )

    df = df.drop("name_lower", "bgg_id_matched", "is_ambiguous")

    # 2. Try fuzzy matching for remaining nulls
    still_missing = df.filter(pl.col("bgg_id").is_null())["name"].unique().to_list()
    if not still_missing:
        return df

    LOGGER.info("Performing fuzzy matching for %d games...", len(still_missing))

    bgg_fuzzy = bgg_lf.with_columns(count=pl.len().over("name")).collect()
    bgg_id_map = dict(
        bgg_fuzzy.filter(pl.col("count") == 1).select("name", "bgg_id").iter_rows(),
    )

    fuzzy_results = []
    for name in still_missing:
        best_match, score = process.extractOne(name, bgg_fuzzy["name"])
        if score >= FUZZY_MATCH_THRESHOLD:
            if bgg_id := bgg_id_map.get(best_match):
                LOGGER.info(
                    "Fuzzy match: '%s' -> '%s' (ID: %d, score: %d)",
                    name,
                    best_match,
                    bgg_id,
                    score,
                )
                fuzzy_results.append({"name": name, "bgg_id_fuzzy": bgg_id})
            else:
                LOGGER.warning(
                    "Fuzzy match skipped: '%s' -> '%s' (score: %d) - ambiguous in BGG.",
                    name,
                    best_match,
                    score,
                )
        else:
            LOGGER.debug(
                "No confident fuzzy match for '%s' (best: '%s', score: %d)",
                name,
                best_match,
                score,
            )

    if fuzzy_results:
        df = (
            df.join(pl.DataFrame(fuzzy_results), on="name", how="left")
            .with_columns(bgg_id=pl.coalesce("bgg_id", "bgg_id_fuzzy"))
            .drop("bgg_id_fuzzy")
        )

    return df


def main() -> None:
    args = arg_parse()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
        stream=sys.stderr,
    )

    if not args.input.exists():
        LOGGER.error("Input file <%s> does not exist.", args.input)
        sys.exit(1)

    LOGGER.info("Processing new reviews from <%s>", args.input)
    new_data = reviews_jl_to_polars(args.input)
    LOGGER.info("Extracted %d items from .jl file", len(new_data))

    # Try to find BGG IDs for new data
    new_data = find_bgg_ids(new_data, args.bgg_games)

    if not args.csv.exists():
        LOGGER.warning("CSV file <%s> does not exist. Creating new one.", args.csv)
        if not args.dry_run:
            args.csv.parent.mkdir(parents=True, exist_ok=True)
            new_data.write_csv(args.csv)
        else:
            print(new_data)
        return

    LOGGER.info("Reading existing data from <%s>", args.csv)
    existing_data = pl.read_csv(args.csv, schema_overrides={"bgg_id": pl.Int64})

    # Combine data using 'diagonal' concatenation
    combined = pl.concat([existing_data, new_data], how="diagonal")

    # Deduplicate by URL and Name
    combined = combined.sort("bgg_id", descending=True, nulls_last=True)
    combined = combined.unique(
        subset=["url", "name"],
        keep="first",
        maintain_order=False,
    )

    # Final sort by date and name for consistent CSV order
    combined = combined.sort("date_published", "name")

    if args.dry_run:
        LOGGER.info("Dry run: not writing to <%s>", args.csv)
        print(combined)
    else:
        LOGGER.info("Writing updated data to <%s>", args.csv)
        combined.write_csv(args.csv)
        LOGGER.info("Successfully updated CSV.")


if __name__ == "__main__":
    main()
