name: Autoupdate dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  auto-update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-uv-env

      - name: Update outdated packages
        run: uv lock --upgrade

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain uv.lock)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      # behaviour if PR already exists: https://github.com/marketplace/actions/create-pull-request#action-behaviour
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: >-
            chore: update dependencies
          title: "[Actions] Auto-Update dependencies"
          body: |
            The following dependencies have been updated.
          branch: chore/update-dependencies
          delete-branch: true
