name: Release

on:
  release:
    types: [ published ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-uv-env
      - name: Build and Publish to pypi
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
